### ISSUE TITLE
NullReferenceException in ContainerProvider.AmbientRequestLifetime

### ISSUE THREAD

**Issue by michael-x** [autofac/Autofac.Web#1] opened 2015-04-16 14:44 UTC
We seem to be getting the following exception every once in a while during application pool recycle events:

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Autofac.Integration.Web.ContainerProvider.get_AmbientRequestLifetime()
   at Autofac.Integration.Web.ContainerProvider.EndRequestLifetime()
   at System.Web.HttpApplication.SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)
```

The AmbientRequestLifetime getter tries to obtain an ILifetimeScope from the current request context and I'm wondering if there are any situations where there is no current request context yet/anymore.

The application is hosted on an IIS 8.5/WS 2012 R2. Around that time the application starts a second log-file which tells me that there seem to be two worker processes active at the same time. What I don't know is, whether this is because of the error above or whether the error above is caused by whatever caused the second worker process to be spawned while the first hasn't finished yet.

**Comment by tillig** [comment] 2015-04-16 14:58
(Yay! First issue!)

There may be a few issues at play, but without a repro, I can only give you a few things to look at or tips based on personal experience:
- **You may get more than one worker process per site/application.** It really depends on the configuration of the server, but one example of where you'd see it is if you [are using web gardens and IIS is configured to allow multiple workers](http://www.iis.net/learn/get-started/planning-your-iis-architecture/understanding-multicore-scaling-on-numa-hardware-with-iis-8). Again, that's just one example; I've seen it happen in other cases, too, under varied circumstances (e.g., if you have the app [configured for "warm start"](http://www.iis.net/learn/get-started/whats-new-in-iis-8/iis-80-application-initialization)).
- **If the app pool recycles during an active request** you might get weirdness, especially if there are async actions going on.
- **If you resolve stuff during app startup** you can run into weirdness if you have any dependencies registered as instance-per-request and you use them during startup. There's no context during startup.
- **HttpModule Init runs once per HttpApplication instance** and you can have multiple application instances in a single app pool. [This SO question has a good answer explaining.](http://stackoverflow.com/questions/3370839/advanced-how-many-times-does-httpmodule-init-method-get-called-during-applica)
- **async/await can be problems** - I've seen times where async/await calls accidentally drop thread context, particularly in WCF. I imagine there's a possibility of that happening in ASP.NET, too.

Generally when I see weird stuff like this it's due to a combination of things (e.g., I have an HttpModule resolving some stuff at app startup and doing something with a static, but there are multiple HttpApplication instances).

Hard to be more specific or point at an exact thing without a repro. Your issue may be something entirely outside these items - again, these are just some shots in the dark based on my experience.

Does that help at all?

**Comment by michael-x** [comment] 2015-04-16 17:51
Looking at the implementation of AmbientRequestLifetime I'm wondering what could cause this to throw an `ArgumentNullException`.

``` C#
109         static ILifetimeScope AmbientRequestLifetime 
110         { 
111             get 
112             { 
113                 return (ILifetimeScope)HttpContext.Current.Items[typeof(ILifetimeScope)]; 
114             } 
115             ...
119         } 
```

The only thing that I can think of is an HttpContext.Current with a `null` value. This would probably mean that there is no current request (e.g. at Application_Start) or get_AmbientRequestLifetime is called from a different thread. As according to the call stack above get_AmbientRequestLifetime gets called by EndRequestLifetime and that in turn only gets called by the ContainerDisposalModule, get_AmbientRequestLifetime should probably guard against this kind of situation, don't you think?

**Comment by tillig** [comment] 2015-04-16 17:56
I suppose we could offer a more informative exception message, but there's not really anything we can do to "fall back" in this case.

If it's happening at application start, for example, that's actually a flaw in the application logic - you'd need to register your dependencies with a different lifetime scope so that doesn't happen. You wouldn't want things to "just work" if the request context disappears.

Even if we provided the better exception, that wouldn't solve the issue you raise - it'd just be a different exception. Again, without a repro, I'm not sure I can provide more help. [Per-request scope is tricky enough that we have a very long FAQ on it.](http://autofac.readthedocs.org/en/v3.5.2/faq/per-request-scope.html) It's kind of up to the application to figure out what happened since there's nothing we know at the Autofac level other than "you're trying to get to the per-request scope and there's no request context."

**Comment by michael-x** [comment] 2015-04-16 18:09
What I don't understand is how the scope of Autofac resolved objects could have an influence on when the EndRequest event of the ContainerDisposal module is fired. I guess that event would be fired whenever IIS/ASP.NET decides.

When looking at ContainerProvider.EndRequestLifetime it may be a good fall back option for AmbientRequestLifetime to return null, when there is no Current HttpContext (and therefore no AmbientRequestLifetime).

``` C#
67         public void EndRequestLifetime() 
68         { 
69             var rc = AmbientRequestLifetime; 
70             if (rc != null) 
71                 rc.Dispose(); 
72         } 
```

**Comment by tillig** [comment] 2015-04-16 18:22
The scope doesn't affect when the EndRequestLifetime event is raised. I apologize for potentially confusing the issue by bringing that discussion in. The point I was trying to make is that it's not just "fall down easy" all the time.

It appears to boil down to EndRequest firing when there is no request context anymore. I'm not sure we can do anything from here. EndRequestLifetime runs when the application EndRequest event is raised. There's always a context there, at least, there always should be. The fact this exception is getting raised indicates something is amiss, and that's not necessarily Autofac's fault. It's actually a larger issue; you may be getting the Autofac exception now, but even if we somehow just swallowed that, it doesn't mean something else wouldn't fall down later because there's no context where there's one expected.

**Without a repro I'm just stabbing in the dark.** I would love to give you a more concrete answer. I would love to say "it's totally safe to just change this" and call it good.

I don't think it is. I think there's something larger going on and changing Autofac to accommodate for it may fix your problem but could affect other apps. Consider that we have > 45,000 downloads of the web integration from NuGet and this is the first instance of this we've run into. At my business I know we have some high-traffic online banking apps running this code in huge farms and we've never seen it. _That's not to say there's no issue or maybe you're just the first to spot it_, just to say we probably need a bit more concrete info about the cause of the issue before we change the behavior of this fairly stable code.

There is not much code in the ContainerDisposalModule. There is also not much code in ContainerProvider. You are free to experiment by creating your own copies of those in your source and modifying the code to see if it resolves the issue. Maybe you'll uncover the root of the problem and be able to fix it.

If you are able to provide a repro or more information about the cause here, I'd be more than happy to work through it with you and come to a good solution. Maybe we do need to guard against something that is a recent change in the way IIS works in Server 2012. But we do need a bit more before making the change.

**Comment by tillig** [comment] 2016-01-12 20:22
Given there's been no repro submitted, I'm going to close this issue. If you can provide a repro so we can work through it, we can reopen at that time.

**Closed as completed by tillig** 2016-01-12 20:22 UTC
Labels: question
